### ISSUE TITLE
Alarm via POCSAG

### ISSUE THREAD

**Issue by poccix** [SituationBoard/SituationBoard#2]
Moin,

als Verbesserung für das SituationBoard wäre die Erweiterung um die Quellressource "POCSAG", für den Empfang von digitalen Meldeempfängern, eine interessante Methode.

Hierdurch können dann sicherlich auch noch mehr Feuerwehren den Anschluss an das SituationBoard finden um im Ernstfall mithilfe dieser Software noch besser Planen und Agieren zu können.

Gruß Lucas

<hr>

Hello,

as an improvement for the SituationBoard, adding the source resource "POCSAG" to receive digital message receivers would be an interesting method.

This means that even more firestations will be able to connect to the SituationBoard in order to be able to plan and act even better with the help of this software in an emergency.

Greetings Lucas

**Comment by Sebastian-Maier** [comment]
Die Alarme (inkl. Einsatzdetails) direkt aus dem digitalen Pager auszulesen wäre für viele vermutlich wirklich der beste und eleganteste Weg: latenzarm, robust, unabhängig von Internet/Mobilfunktnetz, ...
(Vorausgesetzt, dass die notwendigen Informationen inkl. Einsatzort in den Nachrichten am Piepser vorliegen und auch auslesbar sind.)

Leider verwenden wir in Bayern aktuell noch analoge 4m FMEs. Sobald bei uns – voraussichtlich dieses Jahr – digitale TETRA Pager eingeführt werden, werde ich aber testen ob man diese Nachrichten auslesen und in Form eines Quell-Plugins für SituationBoard nutzbar machen kann/darf.

POCSAG Meldern wie dem "Swissphone Boss 925 V" scheinen andere aber schon erfolgreich Nachrichten über die COM/RS232-Schnittstelle entlockt zu haben:

[https://www.funkmeldesystem.de/archive/index.php/t-52025.html](https://www.funkmeldesystem.de/archive/index.php/t-52025.html)

Allerdings muss der Melder scheinbar für die “Meldungsausgabe" entsprechend geeignet und programmiert sein.

**Comment by Sebastian-Maier** [comment]
@poccix 
Du hattest ja damals einen SourceDriver und MessageParser für POCSAG erstellt, der nach etwas Unterstützung auch erfolgreich lief: [https://github.com/poccix/SituationBoard](https://github.com/poccix/SituationBoard)

Läuft SituationBoard seitdem problemlos bei euch?
Hast du Interesse daran deine Plugins via pull request up-stream zu bringen und damit auch anderen zur Verfügung zu stellen? Das würde ggf. auch die Pflege/Wartung erleichtern (z.B. bei zukünftigen Updates von SituationBoard).

Solltest du kein Interesse daran haben, werde ich dieses issue zeitnah schließen.
