### ISSUE TITLE
Communication platform

### ISSUE THREAD

**Issue by Phill93** [SituationBoard/SituationBoard#6]
For direct communication, github is not so suitable. What do you think about creating a Slack workspack?

**Comment by noffycws** [comment]
+1

**Comment by Sebastian-Maier** [comment]
@poccix @noffycws @Phill93 @Grave79

Are there any opinions or preferred communication channels/tools?
Slack looks very nice (and I am willing to give it a try) but it has a 10.000 message limit that could theoretically become a problem at some point [1, 2]. (?)

[1] [https://slack.com/intl/en-de/pricing](https://slack.com/intl/en-de/pricing)
[2] [https://medium.com/@gabriel_wilkes/why-tech-groups-can-get-away-with-using-slack-for-free-but-open-source-projects-and-businesses-of-96c427aaefbb](https://medium.com/@gabriel_wilkes/why-tech-groups-can-get-away-with-using-slack-for-free-but-open-source-projects-and-businesses-of-96c427aaefbb)

**Comment by Sebastian-Maier** [comment]
### Preliminary List of Communication Tools/Platforms
A incomplete list of possible tools (additions and corrections are welcome):

**[Slack](https://slack.com)**
- focus on SW teams / collaboration
- free with 10.000 message archive limit
- video/audio calls

**[Mattermost](https://mattermost.com)**
- focus on SW teams / collaboration
- open source, self hosted
- free with unlimited archive
- **no** video/audio calls (link to external tools only ?)

**[GitHub Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions) & [GitHub Team Discussions](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-team-discussions)**
- free with unlimited users and history
- good GitHub integration / same platform
- **no** client app
- **no** video/audio calls

**[Rocket.chat](https://rocket.chat)**
- focus on SW teams / collaboration
- open source, self hosted
- video/audio calls via Jitsi Meet (integrated ?)

**[Chanty](https://www.chanty.com/)**
- focus on SW teams / collaboration
- up to 10 users are free
- video/audio calls
- has a task manager

**[Discord](https://discord.com)**
- free
- video/audio calls

### Comparisons between Tools and other Links
- [Rocket.chat vs. Mattermost](https://digital-magazin.de/rocketchat-vs-mattermost-vergleich/)
- [Slack Alternatives](https://www.heise.de/tipps-tricks/Slack-Alternativen-Die-5-besten-Team-Messenger-4233366.html)

### Other Communication Tools/Platforms
- [Jitsi Meet](https://meet.jit.si)
- Signal
- WhatsApp
- Skype
- ...

**Comment by Sebastian-Maier** [comment]
As discussed in the (online) kickoff meeting, we will use a **self-hosted Mattermost** instance for internal team communication.

In case you want to take part in team conversations, **ask** one of the team members or maintainers **for an invitation to our Mattermost server/team**.

Should this solution cause unforeseen problems in the future, we could also consider private [GitHub Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions) like [GitHub Team Discussions](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-team-discussions) as an alternative.
